export const config = {
  startingCash: 1000,
  startingPrice: 100,
  weeks: 4,
  daysPerWeek: 5,
  cardsPerDay: 10,
  forcedRed: 1,
  forcedGreen: 1,
  weekTargets: [1500, 1900, 2400, 3000],
  eventChance: 0.4,
}

export const attributes = {
  monkey: {
    label: '猴',
    comboHint: '连击：有概率翻转红绿',
  },
  bear: {
    label: '熊',
    comboHint: '连击：跌幅更深',
  },
  bull: {
    label: '牛',
    comboHint: '连击：涨幅更大',
  },
}

export const specialRules = {
  echo: '上一张同色时有50%概率额外±2%',
  swing: '上一张异色时有50%概率额外±3%',
  booster: '有50%概率使波动额外增加25%',
  brake: '有50%概率使波动额外减少25%',
  reverseNext: '有50%概率反转下一张涨跌方向',
  doubleNext: '有50%概率使下一张波动翻倍',
  split: '本张60%立即生效，40%在下一张后追加',
  buffer: '本张70%立即生效，30%在日终追加',
  ghost: '50%概率本张不生效，但下一张追加±2%',
  shield: '若下一张异色，下一张幅度×0.85',
  latch: '若下一张同色，下一张幅度×1.15',
}

export const cards = [
  {
    id: 'g-bull-uptick',
    name: '上冲电讯',
    color: 'green',
    attr: 'bull',
    min: 5,
    max: 10,
    special: 'echo',
  },
  {
    id: 'g-bull-volume',
    name: '成交量激增',
    color: 'green',
    attr: 'bull',
    min: 8,
    max: 15,
    special: 'booster',
  },
  {
    id: 'g-bull-steady',
    name: '稳步买单',
    color: 'green',
    attr: 'bull',
    min: 5,
    max: 9,
    special: 'brake',
  },
  {
    id: 'g-bull-insider',
    name: '内线推力',
    color: 'green',
    attr: 'monkey',
    min: 6,
    max: 12,
    special: 'swing',
  },
  {
    id: 'g-bull-climb',
    name: '攀升回路',
    color: 'green',
    attr: 'bull',
    min: 7,
    max: 13,
    special: 'echo',
  },
  {
    id: 'g-monkey-echo',
    name: '镜像买单',
    color: 'green',
    attr: 'monkey',
    min: 5,
    max: 11,
    special: 'reverseNext',
  },
  {
    id: 'g-monkey-glitch',
    name: '故障尖刺',
    color: 'green',
    attr: 'monkey',
    min: 7,
    max: 14,
    special: 'doubleNext',
  },
  {
    id: 'g-bear-relief',
    name: '空头回补',
    color: 'green',
    attr: 'bear',
    min: 6,
    max: 10,
    special: 'swing',
  },
  {
    id: 'g-bear-cover',
    name: '空头回补',
    color: 'green',
    attr: 'bear',
    min: 5,
    max: 9,
    special: 'echo',
  },
  {
    id: 'g-monkey-feint',
    name: '猴子佯攻',
    color: 'green',
    attr: 'monkey',
    min: 6,
    max: 12,
    special: 'booster',
  },
  {
    id: 'g-bull-ramp',
    name: '拉升信号',
    color: 'green',
    attr: 'bull',
    min: 9,
    max: 15,
    special: 'doubleNext',
  },
  {
    id: 'g-bull-loop',
    name: '绿色回路',
    color: 'green',
    attr: 'bull',
    min: 5,
    max: 10,
    special: 'reverseNext',
  },
  {
    id: 'g-monkey-pulse',
    name: '脉冲跳涨',
    color: 'green',
    attr: 'monkey',
    min: 8,
    max: 14,
    special: 'swing',
  },
  {
    id: 'g-bear-calm',
    name: '平静回补',
    color: 'green',
    attr: 'bear',
    min: 5,
    max: 8,
    special: 'brake',
  },
  {
    id: 'g-monkey-tilt',
    name: '倾斜上冲',
    color: 'green',
    attr: 'monkey',
    min: 7,
    max: 12,
    special: 'echo',
  },
  {
    id: 'r-bear-dump',
    name: '红色抛压',
    color: 'red',
    attr: 'bear',
    min: -15,
    max: -8,
    special: 'booster',
  },
  {
    id: 'r-bear-slip',
    name: '滑落线',
    color: 'red',
    attr: 'bear',
    min: -12,
    max: -6,
    special: 'echo',
  },
  {
    id: 'r-bear-crush',
    name: '碾压卖单',
    color: 'red',
    attr: 'bear',
    min: -14,
    max: -9,
    special: 'doubleNext',
  },
  {
    id: 'r-bear-drain',
    name: '抽干抛售',
    color: 'red',
    attr: 'bear',
    min: -10,
    max: -6,
    special: 'brake',
  },
  {
    id: 'r-bear-hammer',
    name: '重锤下压',
    color: 'red',
    attr: 'bear',
    min: -13,
    max: -7,
    special: 'swing',
  },
  {
    id: 'r-monkey-flip',
    name: '翻转陷阱',
    color: 'red',
    attr: 'monkey',
    min: -12,
    max: -6,
    special: 'reverseNext',
  },
  {
    id: 'r-monkey-glitch',
    name: '故障下挫',
    color: 'red',
    attr: 'monkey',
    min: -14,
    max: -8,
    special: 'doubleNext',
  },
  {
    id: 'r-monkey-feint',
    name: '猴子佯攻',
    color: 'red',
    attr: 'monkey',
    min: -11,
    max: -5,
    special: 'echo',
  },
  {
    id: 'r-bull-trick',
    name: '牛市诡计',
    color: 'red',
    attr: 'bull',
    min: -10,
    max: -5,
    special: 'swing',
  },
  {
    id: 'r-bull-leak',
    name: '泄漏下行',
    color: 'red',
    attr: 'bull',
    min: -9,
    max: -5,
    special: 'brake',
  },
  {
    id: 'r-bull-fade',
    name: '衰减出货',
    color: 'red',
    attr: 'bull',
    min: -12,
    max: -7,
    special: 'booster',
  },
  {
    id: 'r-monkey-tilt',
    name: '倾斜下压',
    color: 'red',
    attr: 'monkey',
    min: -11,
    max: -6,
    special: 'swing',
  },
  {
    id: 'r-bear-bleed',
    name: '失血下跌',
    color: 'red',
    attr: 'bear',
    min: -13,
    max: -8,
    special: 'reverseNext',
  },
  {
    id: 'r-bull-shake',
    name: '震荡洗盘',
    color: 'red',
    attr: 'bull',
    min: -14,
    max: -9,
    special: 'doubleNext',
  },
  {
    id: 'r-monkey-pinch',
    name: '卡位下落',
    color: 'red',
    attr: 'monkey',
    min: -9,
    max: -5,
    special: 'brake',
  },
  {
    id: 'r-bear-break',
    name: '破位下行',
    color: 'red',
    attr: 'bear',
    min: -15,
    max: -10,
    special: 'booster',
  },
  {
    id: 'r-bull-sink',
    name: '牛市下沉',
    color: 'red',
    attr: 'bull',
    min: -12,
    max: -6,
    special: 'echo',
  },
  {
    id: 'r-monkey-jam',
    name: '阻塞下压',
    color: 'red',
    attr: 'monkey',
    min: -10,
    max: -6,
    special: 'swing',
  },
  {
    id: 'r-bear-knife',
    name: '下坠飞刀',
    color: 'red',
    attr: 'bear',
    min: -15,
    max: -11,
    special: 'booster',
  },
  {
    id: 'g-quantum-boost',
    name: '量子提速',
    color: 'green',
    attr: 'bull',
    min: 6,
    max: 11,
    special: 'split',
  },
  {
    id: 'g-darkpool-accumulate',
    name: '暗池吸筹',
    color: 'green',
    attr: 'bull',
    min: 5,
    max: 9,
    special: 'buffer',
  },
  {
    id: 'g-lightcone-guard',
    name: '光锥护盘',
    color: 'green',
    attr: 'bear',
    min: 5,
    max: 10,
    special: 'shield',
  },
  {
    id: 'g-mirror-flicker',
    name: '镜像闪烁',
    color: 'green',
    attr: 'monkey',
    min: 6,
    max: 12,
    special: 'ghost',
  },
  {
    id: 'g-mainnet-merge',
    name: '主网聚合',
    color: 'green',
    attr: 'bull',
    min: 7,
    max: 13,
    special: 'latch',
  },
  {
    id: 'g-particle-arch',
    name: '微粒上拱',
    color: 'green',
    attr: 'monkey',
    min: 5,
    max: 10,
    special: 'split',
  },
  {
    id: 'g-protocol-heat',
    name: '协议热区',
    color: 'green',
    attr: 'bull',
    min: 8,
    max: 14,
    special: 'buffer',
  },
  {
    id: 'g-tunnel-calibrate',
    name: '隧穿校准',
    color: 'green',
    attr: 'bear',
    min: 6,
    max: 11,
    special: 'ghost',
  },
  {
    id: 'g-lattice-lift',
    name: '晶格缓升',
    color: 'green',
    attr: 'bull',
    min: 4,
    max: 8,
    special: 'shield',
  },
  {
    id: 'g-bull-beacon',
    name: '多头信标',
    color: 'green',
    attr: 'bull',
    min: 7,
    max: 12,
    special: 'latch',
  },
  {
    id: 'r-phase-drop',
    name: '相位下挫',
    color: 'red',
    attr: 'bear',
    min: -6,
    max: -11,
    special: 'split',
  },
  {
    id: 'r-darknet-vent',
    name: '黑网泄压',
    color: 'red',
    attr: 'bear',
    min: -7,
    max: -12,
    special: 'buffer',
  },
  {
    id: 'r-entropy-retrace',
    name: '熵增回撤',
    color: 'red',
    attr: 'bull',
    min: -5,
    max: -9,
    special: 'shield',
  },
  {
    id: 'r-noise-collapse',
    name: '噪声塌陷',
    color: 'red',
    attr: 'monkey',
    min: -6,
    max: -11,
    special: 'ghost',
  },
  {
    id: 'r-reverse-drift',
    name: '逆向漂移',
    color: 'red',
    attr: 'bear',
    min: -8,
    max: -13,
    special: 'latch',
  },
  {
    id: 'r-fault-slide',
    name: '断层滑移',
    color: 'red',
    attr: 'bear',
    min: -7,
    max: -12,
    special: 'split',
  },
  {
    id: 'r-bandwidth-choke',
    name: '带宽窒息',
    color: 'red',
    attr: 'monkey',
    min: -6,
    max: -10,
    special: 'buffer',
  },
  {
    id: 'r-darkline-diffuse',
    name: '暗线扩散',
    color: 'red',
    attr: 'bull',
    min: -5,
    max: -10,
    special: 'shield',
  },
  {
    id: 'r-cooldown-fall',
    name: '冷却坠落',
    color: 'red',
    attr: 'bear',
    min: -9,
    max: -14,
    special: 'ghost',
  },
  {
    id: 'r-yaw-slide',
    name: '偏航下滑',
    color: 'red',
    attr: 'monkey',
    min: -6,
    max: -11,
    special: 'latch',
  },
]

export const events = [
  {
    id: 'short-only',
    name: '只能做空',
    desc: '只有下跌才盈利',
    modifiers: { profitMultiplier: -1 },
  },
  {
    id: 'circuit-breaker',
    name: '熔断',
    desc: '每张卡最大波动 8%',
    modifiers: { clampAbs: 8 },
  },
  {
    id: 'dry-liquidity',
    name: '流动性枯竭',
    desc: '所有波动降低 30%',
    modifiers: { globalMultiplier: 0.7 },
  },
  {
    id: 'bull-run',
    name: '牛市冲刺',
    desc: '第一张绿卡额外 +5%',
    modifiers: { firstGreenBonus: 5, bullBoost: 0.1 },
  },
  {
    id: 'bear-bite',
    name: '熊咬',
    desc: '第一张红卡额外 -5%',
    modifiers: { firstRedBonus: -5, bearBoost: 0.1 },
  },
  {
    id: 'monkey-glitch',
    name: '猴子故障',
    desc: '猴连击更易触发反转',
    modifiers: { monkeyFlipBonus: 0.25 },
  },
  {
    id: 'media-frenzy',
    name: '媒体狂热',
    desc: '所有波动提高 30%',
    modifiers: { globalMultiplier: 1.3 },
  },
  {
    id: 'audit-tax',
    name: '审计税',
    desc: '盈利部分额外扣 10%',
    modifiers: { taxRate: 0.1 },
  },
  {
    id: 'mid-reshuffle',
    name: '中段重排',
    desc: '第5张执行后重洗剩余牌序',
  },
  {
    id: 'freeze-beat',
    name: '冻结一拍',
    desc: '第4张牌效果被强制为0',
  },
  {
    id: 'tail-echo',
    name: '尾奏回声',
    desc: '最后一张牌追加40%同向效果',
  },
  {
    id: 'mirror-noise',
    name: '镜像噪声',
    desc: '第2张的50%效果在第6张再次出现',
  },
  {
    id: 'soft-retrace',
    name: '软性回撤',
    desc: '当日涨跌幅超±8%时回补20%幅度',
  },
]
